# Generated by Django 4.2.4 on 2023-09-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Income_Management', '0002_income_created_at_income_date_income_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
