# Generated by Django 4.2.4 on 2023-09-09 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Income_Management', '0003_alter_income_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_source',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
